In [2]:
#Import librabires
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset
import ast

#Load datasets
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Clean data date
df.job_posted_date = pd.to_datetime(df['job_posted_date'])

c:\Users\hieno\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## 🟩 Select First 5 Rows with .iloc() (2.1.1) - Problem

Select and display the job_title and job_location columns for the first 5 rows of the DataFrame using the iloc method

In [3]:
df.info()
# df.iloc[0:5, 1:3]
df.iloc[:5, [1,2]]

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

,job_title,job_location
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT"
1,Data Analyst,"Guadalajara, Jalisco, Mexico"
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany"
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX"
4,Data Engineer- Sr Jobs,"Washington, DC"

## 🟩 Get Rows and Columns with .loc() (2.1.2) - Problem

Retrieve the columns starting with job_title all the way to job_posted_date for rows with an index of 5 to 9. Use the loc method.

In [4]:
df.loc[5:9, 'job_title':'job_posted_date']

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date
5,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59
6,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18
7,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49
8,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34
9,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57

## 🟨 First 15 Rows in US (2.1.3) - Problem

Retrieve the job_title and salary_year_avg for the first 15 rows where the job_country is 'United States'. Use the iloc method.

In [5]:
#Job in United States
df_us = df[df['job_country'] == 'United States']
# df.iloc[:15, [1, 12]]
df_us.iloc[:15][['job_title', 'salary_year_avg']]

                                            job_title  salary_year_avg
0   Senior Clinical Data Engineer / Principal Clin...              NaN
3   LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...              NaN
5                                   GCP Data Engineer              NaN
6                   Senior Data Engineer  - GCP Cloud              NaN
9                                   Data Scientist II              NaN
11                                      Data Engineer              NaN
13                               Senior Data Engineer              NaN
17                             Data Science Team Lead              NaN
26                                      Data Engineer              NaN
27  Principal Data Engineer (Lead), Knowledge Grap...              NaN
30     Senior Data Engineer (Work from home Eligible)              NaN
32   Sr. Data Scientist (NLP) - Full-time / Part-time              NaN
35                        Data Engineer - Royal Canin              NaN
36                                       Data Analyst              NaN
37                     Data Engineer III - Now Hiring              NaN

## 🟥 Filter by Date (2.1.4) - Problem

Select and display the job_title, job_location, and job_posted_date columns for rows where the job_posted_date is after '2023-05-01' using the loc method.

In [6]:
#Filter with conditions: job_posted_date is after '2023-05-01'
#Method 1:
# df_conditions = df[df['job_posted_date'] > '2023-05-01']
# df_conditions.loc[:, ['job_title', 'job_location', 'job_posted_date']]

#Method2:
# df[df['job_posted_date'] > '2023-05-01'][['job_title', 'job_location', 'job_posted_date']]

#Method 3:
df[df['job_posted_date'] > '2023-05-01'].loc[:, ['job_title', 'job_location', 'job_posted_date']]

,job_title,job_location,job_posted_date
0,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",2023-06-16 13:44:15
2,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",2023-10-10 13:14:55
3,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",2023-07-04 13:01:41
4,Data Engineer- Sr Jobs,"Washington, DC",2023-08-07 14:29:36
5,GCP Data Engineer,Anywhere,2023-11-07 14:01:59
...,...,...,...
785694,Data Engineer,"Graz, Austria",2023-05-07 07:07:37
785696,Senior Analytics Engineer,"Colombia, Huila, Colombia",2023-10-23 06:31:25
785698,"Data Engineer, Gerencia Business Intelligence","Las Condes, Chile",2023-08-09 06:32:00
785701,"Data Engineer, Gerencia Business Intelligence","Santiago, Chile",2023-08-09 06:31:57
785706,Junior Data Engineer,"Lima, Peru",2023-11-08 06:34:48