In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df.job_posted_date = pd.to_datetime(df['job_posted_date'])

## 🟩 Drop Missing Values (2.3.1) - Problem

Create a copy of the DataFrame and drop rows where the salary_year_avg column has missing values. Display the first 5 rows of the cleaned DataFrame.

In [22]:
# df_copy = df.copy()
# df_cleaned = df_copy.dropna(subset=['salary_year_avg'])
# df_cleaned.head(5)

df_copied = df.copy()
df_copied = df_copied.dropna(subset = 'salary_year_avg')

df_copied.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."

## 🟩 Random Sample of DataFrame (2.3.2) - Problem

Create a new DataFrame that is a random sample of 10% of the original DataFrame. Display the first 5 rows of the sampled DataFrame.

In [29]:
df_sample = df.sample(frac=0.1)

df_sample.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
289435,Data Engineer,Data Engineer,"Birmingham, AL",via Nexxt,Full-time,False,"Illinois, United States",2023-07-29 17:07:36,True,False,United States,NaN,NaN,NaN,TEKsystems,"['azure', 'power bi']","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
441350,Senior Data Scientist,Senior Data Scientist,"Morrisville, NC",via BeBee,Full-time,False,"New York, United States",2023-08-27 16:02:49,False,False,United States,NaN,NaN,NaN,ASRC Federal Holding Company,"['sql', 'r', 'python', 'oracle', 'excel']","{'analyst_tools': ['excel'], 'cloud': ['oracle..."
176171,Senior Data Analyst,"Senior Data Analyst, Puffy - Powered By Qureos",Abu Dhabi - United Arab Emirates,via LinkedIn,NaN,False,United Arab Emirates,2023-02-08 23:46:12,False,False,United Arab Emirates,NaN,NaN,NaN,Qureos,"['sql', 'excel', 'atlassian', 'asana', 'slack']","{'analyst_tools': ['excel'], 'async': ['asana'..."
362061,Data Analyst,Internship Data Analytics,"Antwerp, Belgium",via BeBee Belgique,Internship,False,Belgium,2023-10-14 00:06:55,False,False,Belgium,NaN,NaN,NaN,Robert Bosch NV/SA,NaN,NaN
15576,Data Engineer,Big Data Engineer Remote,"Thane, Maharashtra, India",via SimplyHired,Full-time,False,India,2023-11-02 13:14:41,True,False,India,NaN,NaN,NaN,Hinopak Motors,"['nosql', 'spark']","{'libraries': ['spark'], 'programming': ['nosq..."

## 🟨 Fill Missing Salaries (2.3.3) - Problem

Create a copy of the original DataFrame and fill in missing values in the salary_year_avg column with the median salary. Display the first 5 rows of the altered DataFrame.

In [37]:
df_copied = df.copy()

#Calculating the median yearly salary
median_salary = df_copied.salary_year_avg.median()

#Fill the missing values in the salary_year_avg column
df_copied['salary_year_avg'] = df_copied['salary_year_avg'].fillna(median_salary)

df_copied.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."