In [1]:
import pandas as pd
import numpy as np
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df.job_posted_date = pd.to_datetime(df['job_posted_date'])

c:\Users\hieno\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## 🟩 Count Job Postings by Title and Country (2.4.1) - Problem

Create a pivot table to count the number of job postings for each job_title_short and job_country. Display the first 10 rows of the resulting pivot table.

In [2]:
pivot_table = df.pivot_table(index = ['job_title_short', 'job_country'], aggfunc = 'size')

pivot_table.head(5)

job_title_short   job_country
Business Analyst  Afghanistan      4
                  Albania         11
                  Algeria         21
                  Angola           1
                  Argentina      453
dtype: int64

## 🟨 Salary Stats by Job Title (2.4.2) - Problem

Create a pivot table to find the maximum, minimum, and average salary_year_avg for each company_name. Display the first 5 rows of the resulting pivot table.

In [15]:
pivot_table = df.pivot_table(values = 'salary_year_avg', index = 'company_name', aggfunc = {'salary_year_avg': ['max', 'min', 'mean']}).sort_values(ascending = False, by = ['max', 'min', 'mean'])

pivot_table.head(5)

                                                  max           mean       min
company_name
East River Electric Power Cooperative, Inc.  960000.0  537000.000000  114000.0
MSP Staffing  LTD                            890000.0  890000.000000  890000.0
Mantys                                       650000.0  650000.000000  650000.0
ReServe                                      585000.0  585000.000000  585000.0
Selby Jennings                               550000.0  204615.384615  100000.0

## 🟥 Sum Salary by Title and Country (2.4.3) - Problem

Create a pivot table to calculate the median of salary_year_avg for each company_name and job_country:

* Filter the pivot table to only include 'Data Scientist' roles.
* Then filter the pivot table to only include company_name with a median salary_year_avg greater than 200,000.
* Display the first 10 rows of the resulting pivot table.

In [33]:
df_DS = df[df['job_title_short'] == 'Data Scientist'].copy()

PT = df_DS.pivot_table(values = 'salary_year_avg', index = ['company_name', 'job_country'], aggfunc = 'median')

PT_filtered = PT[PT['salary_year_avg'] > 200000].copy()

PT_filtered.head(10).sort_values(ascending = False, by = 'salary_year_avg')

                                   salary_year_avg
company_name        job_country
Analog Devices, Inc United States         375000.0
Algo Capital Group  United States         350000.0
                    Sudan                 325000.0
Airtable            United States         233500.0
Amadeus Search      United States         232500.0
ACT                 Sudan                 225000.0
                    United States         225000.0
Airtable            Sudan                 215500.0
Airbnb              United States         212500.0
Abbott              United States         204000.0