In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## 🟩 Concat Job Postings (2.8.1) - Problem

Concatenate two DataFrames to analyze job postings for Data Scientists and Data Analysts:

* Create one DataFrame with job postings for Data Scientists named data_scientist_df and another for Data Analysts named data_analyst_df.
* Concatenate them and display the combined DataFrame called combined_df.

In [ ]:
# data_scientist_df = df[df['job_title_short'] == 'Data Scientist']
# data_analyst_df = df[df['job_title_short'] == 'Data Analyst']
job_title = df.job_title_short.unique()

dict_jobs_title = {job: df[df['job_title_short'] == job] for job in job_title}

combined_df = pd.concat([dict_jobs_title['Data Analyst'], dict_jobs_title['Data Scientist']], ignore_index=True)

combined_df

       job_title_short  ...                                    job_type_skills
0         Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
1         Data Analyst  ...  {'analyst_tools': ['excel', 'power bi', 'sap']...
2         Data Analyst  ...  {'analyst_tools': ['excel', 'looker', 'tableau...
3         Data Analyst  ...                           {'programming': ['sql']}
4         Data Analyst  ...                         {'analyst_tools': ['sap']}
...                ...  ...                                                ...
368356  Data Scientist  ...                           {'programming': ['sql']}
368357  Data Scientist  ...  {'analyst_tools': ['sap', 'word', 'powerpoint'...
368358  Data Scientist  ...         {'programming': ['python', 'matlab', 'r']}
368359  Data Scientist  ...  {'analyst_tools': ['power bi', 'tableau', 'wor...
368360  Data Scientist  ...  {'cloud': ['bigquery'], 'libraries': ['gdpr'],...

[368361 rows x 17 columns]

## 🟨 Concat Monthly Postings (2.8.2) - Problem

Concatenate DataFrames to analyze job postings by month:

* Create DataFrames for job postings for the last quarter (October, November, and December). These are respectively called oct_df, nov_df, and dec_df.
* Concatenate them and display the combined DataFrame named combined_df.

In [ ]:
# oct_df = df[df['job_posted_date'].dt.month == 10]
# nov_df = df[df['job_posted_date'].dt.month == 11]
# dec_df = df[df['job_posted_date'].dt.month == 12]
# combined_df = pd.concat([oct_df, nov_df, dec_df], ignore_index=True)
# combined_df

df['job_posted_month'] = df['job_posted_date'].dt.month_name()

months = df['job_posted_month'].unique()

dict_month = {month: df[df['job_posted_month'] == month] for month in months}

oct_df, nov_df, dec_df = dict_month['October'], dict_month['November'], dict_month['December']

combined_df = pd.concat([oct_df, nov_df, dec_df], ignore_index=True)

combined_df

         job_title_short  ... job_posted_month
0          Data Engineer  ...          October
1          Data Engineer  ...          October
2           Data Analyst  ...          October
3           Data Analyst  ...          October
4           Data Analyst  ...          October
...                  ...  ...              ...
187359     Data Engineer  ...         December
187360     Data Engineer  ...         December
187361      Data Analyst  ...         December
187362  Business Analyst  ...         December
187363    Cloud Engineer  ...         December

[187364 rows x 18 columns]

## 🟨 Concat Job Types (2.8.3) - Problem

Concatenate DataFrames to analyze job postings for different job types:

* Create DataFrames for 'Full-time' roles (called full_time_df) and 'Part-time' roles (called part_time_df) job postings.
* Concatenate them and display the combined DataFrame named combined_df.

In [28]:
full_time_df = df[df['job_schedule_type'] == 'Full-time'].copy()
part_time_df = df[df['job_schedule_type'] == 'Part-time'].copy()

combined_df = pd.concat([full_time_df, part_time_df], ignore_index=True)
combined_df

             job_title_short  ... job_posted_month
0       Senior Data Engineer  ...             June
1               Data Analyst  ...          January
2              Data Engineer  ...          October
3              Data Engineer  ...             July
4              Data Engineer  ...           August
...                      ...  ...              ...
709603         Data Engineer  ...          October
709604  Senior Data Engineer  ...          October
709605        Data Scientist  ...          January
709606      Business Analyst  ...              May
709607        Data Scientist  ...          January

[709608 rows x 18 columns]