In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset
import ast

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

## 🟩 Convert Date to String (2.10.1) - Problem

Convert the job_posted_date column to a string format 'YYYY-MM-DD' and create a new column job_posted_date_str.

In [35]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda x: x.strftime('%Y - %m - %d'))

In [36]:
df[['job_posted_date', 'job_posted_date_str']].head()

      job_posted_date job_posted_date_str
0 2023-06-16 13:44:15      2023 - 06 - 16
1 2023-01-14 13:18:07      2023 - 01 - 14
2 2023-10-10 13:14:55      2023 - 10 - 10
3 2023-07-04 13:01:41      2023 - 07 - 04
4 2023-08-07 14:29:36      2023 - 08 - 07

## 🟨 Days Since Posted (2.10.2) - Problem

Calculate the number of days since each job was posted. Create a new column days_since_posted that contains this value. Use the job_posted_date column.

Note: You need to import the datetime library and use the datetime module to get the current date using .now().

In [63]:
from datetime import datetime

current_date = pd.to_datetime('today')
# current_date = datetime.now()
df['days_since_posted'] = df['job_posted_date'].apply(lambda date: (current_date - date).days)
df[['job_posted_date', 'days_since_posted']].head()

      job_posted_date  days_since_posted
0 2023-06-16 13:44:15               1131
1 2023-01-14 13:18:07               1284
2 2023-10-10 13:14:55               1015
3 2023-07-04 13:01:41               1113
4 2023-08-07 14:29:36               1079

## 🟥 Salary Category (2.10.3) - Problem

* Create a copy of the DataFrame called df_filtered and drop the NaN values for salary_year_avg.
* Then, create a new column salary_category that categorizes the salary_year_avg into three categories: 'Low' for salaries less than 60,000, 'Medium' for salaries between 60,000 and 100,000, and 'High' for salaries greater than 100,000.
* Then show the df_filtered DataFrame and the salary_year_avg and salary_category columns.

In [ ]:
# df_filtered = df[pd.notna(df['salary_year_avg'])].copy()
df_filtered = df.copy().dropna(subset='salary_year_avg')

df_filtered['salary_category'] = df_filtered['salary_year_avg'].apply(lambda salary: 'High' if salary > 100000 else 'Medium' if 60000 < salary < 100000 else 'Low')
df_filtered[['salary_category', 'salary_year_avg']].head()

    salary_category  salary_year_avg
28             High         109500.0
77             High         140000.0
92             High         120000.0
100            High         228222.0
109          Medium          89000.0